### ISSUE TITLE
MQTT_Connect with zero length password fails assert

### ISSUE THREAD

**Issue by jondurrant** [FreeRTOS/coreMQTT-Agent#79]
MQTT_Connect seems to have an assert within it that fails on zero length password. A zero length password should be valid?

coreMQTT-Agent v1.2.0
coreMQTT current head

**Comment by AniruddhaKanhere** [comment]
Hello @jondurrant, thank you for bringing this to our attention.
We are looking into it and will get back to you soon.

Without a deep dive into the code base, I think `coreMQTT` does allow 0 length passwords (Is that same as no password?). You can use that by setting the variables like following:
```
pConnectInfo->pPassword = NULL;
pConnectInfo->passwordLength = 0;
```

**Comment by jondurrant** [comment]
Thanks for the response.  I've set length to zero but the password actually
points to a char array with first value as zero. This worked on v1.1.0 but
on v1.2.0 is failing a new assert, deep in coreMQTT.

Jon

**Comment by jondurrant** [comment]
Closing as found issue is actual that TransportInterface_t.writev is no longer optional and must be provided. This is causing intermittent failures, but an issue ith coreMQTT rather than coreMQTT-Agent.

**Comment by AniruddhaKanhere** [comment]
Hello @jondurrant,
Thank you for root causing the issue (apologies as I was out of office and was unable to reply sooner).

`writev` is actually optional. You can set that to `NULL` in case you do not have an implementation for it.
It is provided in case a user wants to improve the speed of communication using [scatter-gather](https://linux.die.net/man/2/writev) approach.

**Comment by jondurrant** [comment]
Thanks Aniruddha

There is a bug in CoreMQTT v2.1.1 which is not initialising the transport
structure. So writev is not initialised with some therefore random
behaviour. I understand a fix is available in a release candidate.

Jon
