### ISSUE TITLE
Could you preapare new patch-release that updates coreMQTT submodule to v2.1.1?

### ISSUE THREAD

**Issue by slapab** [FreeRTOS/coreMQTT-Agent#86]
I want to use coreMQTT-Agent in my project and I would like to have the latest coreMQTT release: **v.2.1.1**.   

Current version of Agent **v1.2.0**  has configured submodule of coreMQTT in way that points to v2.1.0. 

Is any chance that you can prepare coreMQTT-Agent patch release that upgrades the submodule of coreMQTT?

**Comment by paulbartell** [comment]
@slapab I will check with the team and see what we can do.

In the mean time, consider submoduling coreMQTT at the same directory level as coreMQTT-Agent and selectively initializing your submodules.
